# Generated by Django 5.2 on 2025-04-20 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('secret_code', models.CharField(max_length=100, unique=True)),
                ('total_rounds', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('min_qualify_marks', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_option', models.CharField(max_length=255)),
                ('other_options', models.JSONField(default=list)),
                ('marks', models.FloatField(default=1.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.round')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('total_score', models.FloatField(default=0.0)),
                ('total_time_taken', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True)),
                ('time_taken', models.FloatField(default=0.0)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.question')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.userquiz')),
            ],
        ),
    ]
